"""empty message

Revision ID: e8d6290bb9d6
Revises: bcc005bc255c
Create Date: 2024-05-30 22:07:32.982457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d6290bb9d6'
down_revision = 'bcc005bc255c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('row_id')

    # ### end Alembic commands ###
